//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc01.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class temperaturetbl
    {
        public int id { get; set; }
        public string recid { get; set; }
        public string recdata { get; set; }
        public Nullable<System.DateTime> calltime { get; set; }
        public Nullable<System.DateTime> resptime { get; set; }
        public string status { get; set; }
    }
}
